name: vd_commmerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  rflutter_alert: ^2.0.4
  carousel_slider: ^4.2.1
  freezed_annotation: ^2.2.0
  dio: ^5.2.1+1
  shared_preferences: ^2.1.2

dev_dependencies: 
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter: 
  uses-material-design: true

